### PR TITLE
Add minimal cloud example

### PR DESCRIPTION
**Pull request by Steven-Chan**

### CODE REVIEW

**Comment by Steven-Chan** [comment]
Found an issue with this example, I am not sure if the issue belongs to server or sdk, but I opened in sdk https://github.com/SkygearIO/skygear-SDK-JS/issues/273.

**Comment by rickmak** [comment]
I got this after `docker-compose up`

```
db_1      | LOG:  database system was interrupted; last known up at 2017-08-02 11:32:55 UTC
plugin_1  | [FATAL tini (5)] exec node_modules/.bin/skygear-node failed: No such file or directory
app_1     | Error loading shared library libczmq.so.3: No such file or directory (needed by /usr/local/bin/skygear-server)
db_1      | LOG:  database system was not properly shut down; automatic recovery in progress
app_1     | Error loading shared library libsodium.so.13: No such file or directory (needed by /usr/local/bin/skygear-server)
db_1      | LOG:  invalid record length at 0/2F2E4B8
db_1      | LOG:  redo is not required
db_1      | LOG:  MultiXact member wraparound protections are now enabled
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_rcvbuf: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_req_relaxed: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_new_checked: symbol not found
db_1      | LOG:  database system is ready to accept connections
app_1     | Error relocating /usr/local/bin/skygear-server: zcert_save: symbol not found
db_1      | LOG:  autovacuum launcher started
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_fd: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_multicast_hops: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_tcp_keepalive_intvl: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zframe_size: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_curve_secretkey: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_router_raw: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_curve_publickey: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_tcp_accept_filter: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_plain_username: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zframe_send: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zframe_new: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_rate: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_affinity: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_wait: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_mechanism: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_connect: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_curve_serverkey: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_ipv4only: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zframe_more: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_affinity: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_tos: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_curve_secretkey: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_sndtimeo: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_req_correlate: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_maxmsgsize: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_reconnect_ivl_max: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcert_public_txt: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_destroy_checked: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_delay_attach_on_connect: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_rcvtimeo: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_plain_server: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_unsubscribe: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_tcp_keepalive: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_gssapi_plaintext: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_rcvtimeo: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_recovery_ivl: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_rcvhwm: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcert_new_from: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_curve_serverkey: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcertstore_new: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_gssapi_server: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_rcvhwm: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_bind: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_zap_domain: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_zap_domain: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_send: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_tcp_keepalive_cnt: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_curve_secretkey_bin: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_xpub_verbose: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsys_init: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_backlog: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcert_load: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_conflate: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_plain_username: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_router_handover: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcert_save_secret: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_tcp_keepalive_intvl: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcert_secret_key: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_plain_password: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_curve_server: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_ipv4only: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcert_dup: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_tcp_keepalive: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_tos: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_identity: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_sndhwm: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_ipv6: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_curve_publickey: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zframe_data: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_reconnect_ivl: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_gssapi_service_principal: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zframe_destroy: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_reconnect_ivl_max: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_maxmsgsize: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zstr_recv: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcert_print: symbol not found
cloud_plugin_1 exited with code 127
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_rcvmore: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zframe_recv: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcert_eq: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zpoller_destroy: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zpoller_add: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_sndbuf: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_sndhwm: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zstr_send: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zpoller_new: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_linger: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsys_shutdown: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_last_endpoint: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcert_destroy: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_type: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_disconnect: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcertstore_destroy: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcert_public_key: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_gssapi_principal: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_plain_server: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_gssapi_principal: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_rcvbuf: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_gssapi_service_principal: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcertstore_print: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_sndtimeo: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_immediate: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_multicast_hops: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zpoller_wait: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_identity: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_recovery_ivl: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcert_new: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_resolve: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_plain_password: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_sndbuf: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_tcp_accept_filter: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcertstore_lookup: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_events: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_linger: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_gssapi_server: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_router_mandatory: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcert_set_meta: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_unbind: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_gssapi_plaintext: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_backlog: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zactor_new: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_tcp_keepalive_cnt: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_tcp_keepalive_idle: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcert_save_public: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_immediate: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_tcp_keepalive_idle: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_attach: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcert_meta: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zactor_destroy: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_rate: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zcertstore_insert: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_subscribe: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_curve_server: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zstr_sendm: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_curve_publickey_bin: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_reconnect_ivl: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_probe_router: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zsock_set_ipv6: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zproxy: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zauth: symbol not found
app_1     | Error relocating /usr/local/bin/skygear-server: zbeacon: symbol not found
```

**Comment by cheungpat** [comment]
@rickmak please review this again, thanks

**Comment by rickmak** [comment]
@Steven-Chan I make a superset PR: https://github.com/SkygearIO/skygear-SDK-JS/pull/282 Please review and merge if ok.

**Pull request closed without merging**
