### PR TITLE
Add api uploadAsset to skygear database

### PR DESCRIPTION
**Pull request by Steven-Chan**
connect #267

### CODE REVIEW

**Comment by rickmak** [comment]
Merge via 873cd73

**Comment by cheungpat** [comment]
For me to access the function `uploadAsset`, I need access to `DatabaseContainer`, which isn’t exposed as far as I know.

**Comment by Steven-Chan** [comment]
@cheungpat what about this?
```
import {DatabaseContainer} from 'skygear/database';

const dbContainer = new DatabaseContainer(skygear);
dbContainer.uploadAsset(...);
```

**Comment by cheungpat** [comment]
> @cheungpat what about this?

is this intended usage?

**Comment by cheungpat** [comment]
@Steven-Chan I need it in browser-land.

i.e. all i have is `<script src="https://cdn.example.com/skygear.min.js"></script>`

**Comment by Steven-Chan** [comment]
@cheungpat 
If we decide not to make upload asset a separated functionality, the undocumented way to do it now is `skygear._db.uploadAsset`.

Otherwise, I would prefer what @rickmak said in #267.

**Comment by Steven-Chan** [comment]
@cheungpat updated

**Comment by cheungpat** [comment]
@rickmak

**Comment by Steven-Chan** [comment]
follow up pr: https://github.com/SkygearIO/skygear-SDK-JS/pull/270

**Pull request closed without merging**
