### PR TITLE
Return error to skygear-server in correct format

### PR DESCRIPTION
**Pull request by cheungpat**
connects #127

### CODE REVIEW

**Comment by oursky-travis** [comment]
@cheungpat, thanks for your PR! By analyzing the annotation information on this pull request, we identified @rickmak to be a potential reviewer

**Comment by ben181231** [comment]
@cheungpat Currently, the `lib/error.js` is imported to container as `ErrorCodes`. Can you also rename it since it is now exporting not only error codes.

**Comment by cheungpat** [comment]
What do you think if I do this:

```js
export const ErrorCodes = { /* ... error codes and value here ... */ };
```

**Comment by ben181231** [comment]
Seems great.

**Comment by cheungpat** [comment]
updated

**Pull request merged**
