### PR TITLE
Fix issue with shared user between containers

### PR DESCRIPTION
**Pull request by b123400**
connect https://github.com/SkygearIO/skygear-SDK-JS/issues/186

### CODE REVIEW

**Comment by oursky-travis** [comment]
@b123400, thanks for your PR! By analyzing the history of the files in this pull request, we identified @cheungpat to be a potential reviewer.

**Comment by cheungpat** [comment]
@b123400 The test program doesn‘t exit after running the test case. Can you take a look?

**Comment by cheungpat** [comment]
In the long run, I think we should have the following hierarchy. But it is okay as is:

* CommonContainer with all the functions for calling actions and handlers
  * Container for client development
  * CloudContainer for cloud code development, with user session storage applicable in cloud code environment

**Comment by b123400** [comment]
@cheungpat Agree, but a little suggestion on naming.
The word "common" should be avoided, because it only means codes is shared between something, any class with subclasses can be called "common".
I think it should be "ClientContainer", "CloudContainer" and "Container".

**Pull request merged**
