### PR TITLE
User bootstrap styling

### LINKED ISSUE #84: Give a bootstrap standard layout to JS Example
http://sdkjsexample.skygeario.com/static/example/record.html

Give something looks "normal"

### PR DESCRIPTION
**Pull request by railsstudent**
Fix #84 
Improve CSS styling of User Discovery page

### CODE REVIEW

**Comment by railsstudent** [comment]
skygear-user-1
skygear-user-2

**Comment by railsstudent** [comment]
skygear-index-1
skygear-index-2

**Comment by railsstudent** [comment]
skygear-role-acl-1
skygear-role-acl-2

**Comment by rickmak** [comment]
Hi @railsstudent,

Thank your PR. It looks good and make the example looks nice.

Since we want to keep a linear git history, would you mind to rebase your commit and squash some WIP commits. It will make things better.

Or if you don't mind. I will squash and commit myself.

**Comment by railsstudent** [comment]
Hi @rickmak,

Please do it on my behalf.  
The truth is I don't know how to do git rebase and squash commits.

Thanks,

Connie

**Comment by rickmak** [comment]
Merge via 06ba05e

Thx @railsstudent contribution.

**Pull request closed without merging**
