### PR TITLE
Make S3 signer respect url prefix

### PR DESCRIPTION
**Pull request by louischan-oursky**
connect #214

### CODE REVIEW

**Comment by oursky-travis** [comment]
@louischan-oursky, thanks for your PR! By analyzing the history of the files in this pull request, we identified @rickmak to be a potential reviewer.

**Comment by louischan-oursky** [comment]
If the prefix includes path, then it is not preserved.

e.g. `https://your-cdn.com/` is preserved but `https://your-cdn.com/static/` is not.

Though I don't know whether prefix is supposed to have path.

**Comment by louischan-oursky** [comment]
@rickmak I just found a bug in my original implementation. It does not handle trailing slash properly. I have updated the PR to fix that.

**Comment by rickmak** [comment]
Merge via 8560c9c

**Pull request closed without merging**
