### PR TITLE
Allow config of pg pool size

### PR DESCRIPTION
**Pull request by ckanthony**
connect #201

### CODE REVIEW

**Comment by oursky-travis** [comment]
@ckanthony, thanks for your PR! By analyzing the history of the files in this pull request, we identified @cheungpat to be a potential reviewer.

**Comment by ckanthony** [comment]
it seems like the build failed on running `npm test`, when I do it locally it does work, any ideas?

**Comment by rickmak** [comment]
I know why. Because the `PG_POOL_MIN` will trigger a connect to non-exist PG endpoint. Modify the .travis.yml yo set `PG_POOL_MIN=0` will solve the problem.

**Comment by rickmak** [comment]
I modify the Makefile and set the `PG_POOL_MIN=0` during test.

**Comment by ckanthony** [comment]
cool, excited thanks.

**Pull request merged**
