### PR TITLE
Update npm, fix audit and update build system for node 10

### PR DESCRIPTION
**Pull request by cheungpat**

### CODE REVIEW

**Comment by cheungpat** [comment]
if this is merged, remind me to create a new pull request for the v1 branch

**Comment by ben181231** [comment]
Seems there is some permission issues and the `postinstall` script does not run after `make vendor`.

See if [this commit](https://github.com/SkygearIO/skygear-SDK-JS/pull/445/commits/5ad4ae3) fix the issue.

By the way, shall we add `npm run audit` in the test job?

**Comment by cheungpat** [comment]
> Seems there is some permission issues and the postinstall script does not run after make vendor. See if this commit fix the issue.

I don’t have the same problem...

**Comment by cheungpat** [comment]
@ben181231 see if this works better

**Pull request merged**
